// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: play-game-data.proto

package com.cauchymop.goblob.proto;

public final class PlayGameData {
  private PlayGameData() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface GameDataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated int32 move = 1;
    java.util.List<java.lang.Integer> getMoveList();
    int getMoveCount();
    int getMove(int index);
  }
  public static final class GameData extends
      com.google.protobuf.GeneratedMessage
      implements GameDataOrBuilder {
    // Use GameData.newBuilder() to construct.
    private GameData(Builder builder) {
      super(builder);
    }
    private GameData(boolean noInit) {}
    
    private static final GameData defaultInstance;
    public static GameData getDefaultInstance() {
      return defaultInstance;
    }
    
    public GameData getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cauchymop.goblob.proto.PlayGameData.internal_static_GameData_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cauchymop.goblob.proto.PlayGameData.internal_static_GameData_fieldAccessorTable;
    }
    
    // repeated int32 move = 1;
    public static final int MOVE_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Integer> move_;
    public java.util.List<java.lang.Integer>
        getMoveList() {
      return move_;
    }
    public int getMoveCount() {
      return move_.size();
    }
    public int getMove(int index) {
      return move_.get(index);
    }
    
    private void initFields() {
      move_ = java.util.Collections.emptyList();;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < move_.size(); i++) {
        output.writeInt32(1, move_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < move_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(move_.get(i));
        }
        size += dataSize;
        size += 1 * getMoveList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.GameData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cauchymop.goblob.proto.PlayGameData.GameData prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cauchymop.goblob.proto.PlayGameData.GameDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cauchymop.goblob.proto.PlayGameData.internal_static_GameData_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cauchymop.goblob.proto.PlayGameData.internal_static_GameData_fieldAccessorTable;
      }
      
      // Construct using com.cauchymop.goblob.proto.PlayGameData.GameData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        move_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cauchymop.goblob.proto.PlayGameData.GameData.getDescriptor();
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.GameData getDefaultInstanceForType() {
        return com.cauchymop.goblob.proto.PlayGameData.GameData.getDefaultInstance();
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.GameData build() {
        com.cauchymop.goblob.proto.PlayGameData.GameData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cauchymop.goblob.proto.PlayGameData.GameData buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cauchymop.goblob.proto.PlayGameData.GameData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.GameData buildPartial() {
        com.cauchymop.goblob.proto.PlayGameData.GameData result = new com.cauchymop.goblob.proto.PlayGameData.GameData(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          move_ = java.util.Collections.unmodifiableList(move_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.move_ = move_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cauchymop.goblob.proto.PlayGameData.GameData) {
          return mergeFrom((com.cauchymop.goblob.proto.PlayGameData.GameData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cauchymop.goblob.proto.PlayGameData.GameData other) {
        if (other == com.cauchymop.goblob.proto.PlayGameData.GameData.getDefaultInstance()) return this;
        if (!other.move_.isEmpty()) {
          if (move_.isEmpty()) {
            move_ = other.move_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMoveIsMutable();
            move_.addAll(other.move_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              ensureMoveIsMutable();
              move_.add(input.readInt32());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              while (input.getBytesUntilLimit() > 0) {
                addMove(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated int32 move = 1;
      private java.util.List<java.lang.Integer> move_ = java.util.Collections.emptyList();;
      private void ensureMoveIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          move_ = new java.util.ArrayList<java.lang.Integer>(move_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<java.lang.Integer>
          getMoveList() {
        return java.util.Collections.unmodifiableList(move_);
      }
      public int getMoveCount() {
        return move_.size();
      }
      public int getMove(int index) {
        return move_.get(index);
      }
      public Builder setMove(
          int index, int value) {
        ensureMoveIsMutable();
        move_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addMove(int value) {
        ensureMoveIsMutable();
        move_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllMove(
          java.lang.Iterable<? extends java.lang.Integer> values) {
        ensureMoveIsMutable();
        super.addAll(values, move_);
        onChanged();
        return this;
      }
      public Builder clearMove() {
        move_ = java.util.Collections.emptyList();;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:GameData)
    }
    
    static {
      defaultInstance = new GameData(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:GameData)
  }
  
  public interface MoveOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .Move.MoveType type = 1;
    boolean hasType();
    com.cauchymop.goblob.proto.PlayGameData.Move.MoveType getType();
    
    // optional .Position position = 2;
    boolean hasPosition();
    com.cauchymop.goblob.proto.PlayGameData.Position getPosition();
    com.cauchymop.goblob.proto.PlayGameData.PositionOrBuilder getPositionOrBuilder();
  }
  public static final class Move extends
      com.google.protobuf.GeneratedMessage
      implements MoveOrBuilder {
    // Use Move.newBuilder() to construct.
    private Move(Builder builder) {
      super(builder);
    }
    private Move(boolean noInit) {}
    
    private static final Move defaultInstance;
    public static Move getDefaultInstance() {
      return defaultInstance;
    }
    
    public Move getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cauchymop.goblob.proto.PlayGameData.internal_static_Move_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cauchymop.goblob.proto.PlayGameData.internal_static_Move_fieldAccessorTable;
    }
    
    public enum MoveType
        implements com.google.protobuf.ProtocolMessageEnum {
      MOVE(0, 0),
      PASS(1, 1),
      ;
      
      public static final int MOVE_VALUE = 0;
      public static final int PASS_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static MoveType valueOf(int value) {
        switch (value) {
          case 0: return MOVE;
          case 1: return PASS;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<MoveType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<MoveType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<MoveType>() {
              public MoveType findValueByNumber(int number) {
                return MoveType.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.cauchymop.goblob.proto.PlayGameData.Move.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final MoveType[] VALUES = {
        MOVE, PASS, 
      };
      
      public static MoveType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private MoveType(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:Move.MoveType)
    }
    
    private int bitField0_;
    // required .Move.MoveType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private com.cauchymop.goblob.proto.PlayGameData.Move.MoveType type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.cauchymop.goblob.proto.PlayGameData.Move.MoveType getType() {
      return type_;
    }
    
    // optional .Position position = 2;
    public static final int POSITION_FIELD_NUMBER = 2;
    private com.cauchymop.goblob.proto.PlayGameData.Position position_;
    public boolean hasPosition() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.cauchymop.goblob.proto.PlayGameData.Position getPosition() {
      return position_;
    }
    public com.cauchymop.goblob.proto.PlayGameData.PositionOrBuilder getPositionOrBuilder() {
      return position_;
    }
    
    private void initFields() {
      type_ = com.cauchymop.goblob.proto.PlayGameData.Move.MoveType.MOVE;
      position_ = com.cauchymop.goblob.proto.PlayGameData.Position.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPosition()) {
        if (!getPosition().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, position_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, position_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Move parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cauchymop.goblob.proto.PlayGameData.Move prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cauchymop.goblob.proto.PlayGameData.MoveOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cauchymop.goblob.proto.PlayGameData.internal_static_Move_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cauchymop.goblob.proto.PlayGameData.internal_static_Move_fieldAccessorTable;
      }
      
      // Construct using com.cauchymop.goblob.proto.PlayGameData.Move.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPositionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = com.cauchymop.goblob.proto.PlayGameData.Move.MoveType.MOVE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (positionBuilder_ == null) {
          position_ = com.cauchymop.goblob.proto.PlayGameData.Position.getDefaultInstance();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cauchymop.goblob.proto.PlayGameData.Move.getDescriptor();
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.Move getDefaultInstanceForType() {
        return com.cauchymop.goblob.proto.PlayGameData.Move.getDefaultInstance();
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.Move build() {
        com.cauchymop.goblob.proto.PlayGameData.Move result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cauchymop.goblob.proto.PlayGameData.Move buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cauchymop.goblob.proto.PlayGameData.Move result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.Move buildPartial() {
        com.cauchymop.goblob.proto.PlayGameData.Move result = new com.cauchymop.goblob.proto.PlayGameData.Move(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (positionBuilder_ == null) {
          result.position_ = position_;
        } else {
          result.position_ = positionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cauchymop.goblob.proto.PlayGameData.Move) {
          return mergeFrom((com.cauchymop.goblob.proto.PlayGameData.Move)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cauchymop.goblob.proto.PlayGameData.Move other) {
        if (other == com.cauchymop.goblob.proto.PlayGameData.Move.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPosition()) {
          mergePosition(other.getPosition());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasType()) {
          
          return false;
        }
        if (hasPosition()) {
          if (!getPosition().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.cauchymop.goblob.proto.PlayGameData.Move.MoveType value = com.cauchymop.goblob.proto.PlayGameData.Move.MoveType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              com.cauchymop.goblob.proto.PlayGameData.Position.Builder subBuilder = com.cauchymop.goblob.proto.PlayGameData.Position.newBuilder();
              if (hasPosition()) {
                subBuilder.mergeFrom(getPosition());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setPosition(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .Move.MoveType type = 1;
      private com.cauchymop.goblob.proto.PlayGameData.Move.MoveType type_ = com.cauchymop.goblob.proto.PlayGameData.Move.MoveType.MOVE;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.cauchymop.goblob.proto.PlayGameData.Move.MoveType getType() {
        return type_;
      }
      public Builder setType(com.cauchymop.goblob.proto.PlayGameData.Move.MoveType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = com.cauchymop.goblob.proto.PlayGameData.Move.MoveType.MOVE;
        onChanged();
        return this;
      }
      
      // optional .Position position = 2;
      private com.cauchymop.goblob.proto.PlayGameData.Position position_ = com.cauchymop.goblob.proto.PlayGameData.Position.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.cauchymop.goblob.proto.PlayGameData.Position, com.cauchymop.goblob.proto.PlayGameData.Position.Builder, com.cauchymop.goblob.proto.PlayGameData.PositionOrBuilder> positionBuilder_;
      public boolean hasPosition() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.cauchymop.goblob.proto.PlayGameData.Position getPosition() {
        if (positionBuilder_ == null) {
          return position_;
        } else {
          return positionBuilder_.getMessage();
        }
      }
      public Builder setPosition(com.cauchymop.goblob.proto.PlayGameData.Position value) {
        if (positionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          position_ = value;
          onChanged();
        } else {
          positionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setPosition(
          com.cauchymop.goblob.proto.PlayGameData.Position.Builder builderForValue) {
        if (positionBuilder_ == null) {
          position_ = builderForValue.build();
          onChanged();
        } else {
          positionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergePosition(com.cauchymop.goblob.proto.PlayGameData.Position value) {
        if (positionBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              position_ != com.cauchymop.goblob.proto.PlayGameData.Position.getDefaultInstance()) {
            position_ =
              com.cauchymop.goblob.proto.PlayGameData.Position.newBuilder(position_).mergeFrom(value).buildPartial();
          } else {
            position_ = value;
          }
          onChanged();
        } else {
          positionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearPosition() {
        if (positionBuilder_ == null) {
          position_ = com.cauchymop.goblob.proto.PlayGameData.Position.getDefaultInstance();
          onChanged();
        } else {
          positionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public com.cauchymop.goblob.proto.PlayGameData.Position.Builder getPositionBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPositionFieldBuilder().getBuilder();
      }
      public com.cauchymop.goblob.proto.PlayGameData.PositionOrBuilder getPositionOrBuilder() {
        if (positionBuilder_ != null) {
          return positionBuilder_.getMessageOrBuilder();
        } else {
          return position_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          com.cauchymop.goblob.proto.PlayGameData.Position, com.cauchymop.goblob.proto.PlayGameData.Position.Builder, com.cauchymop.goblob.proto.PlayGameData.PositionOrBuilder> 
          getPositionFieldBuilder() {
        if (positionBuilder_ == null) {
          positionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.cauchymop.goblob.proto.PlayGameData.Position, com.cauchymop.goblob.proto.PlayGameData.Position.Builder, com.cauchymop.goblob.proto.PlayGameData.PositionOrBuilder>(
                  position_,
                  getParentForChildren(),
                  isClean());
          position_ = null;
        }
        return positionBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Move)
    }
    
    static {
      defaultInstance = new Move(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Move)
  }
  
  public interface PositionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 x = 1;
    boolean hasX();
    int getX();
    
    // required int32 y = 2;
    boolean hasY();
    int getY();
  }
  public static final class Position extends
      com.google.protobuf.GeneratedMessage
      implements PositionOrBuilder {
    // Use Position.newBuilder() to construct.
    private Position(Builder builder) {
      super(builder);
    }
    private Position(boolean noInit) {}
    
    private static final Position defaultInstance;
    public static Position getDefaultInstance() {
      return defaultInstance;
    }
    
    public Position getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cauchymop.goblob.proto.PlayGameData.internal_static_Position_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cauchymop.goblob.proto.PlayGameData.internal_static_Position_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 x = 1;
    public static final int X_FIELD_NUMBER = 1;
    private int x_;
    public boolean hasX() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getX() {
      return x_;
    }
    
    // required int32 y = 2;
    public static final int Y_FIELD_NUMBER = 2;
    private int y_;
    public boolean hasY() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public int getY() {
      return y_;
    }
    
    private void initFields() {
      x_ = 0;
      y_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasX()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasY()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, y_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, x_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, y_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.cauchymop.goblob.proto.PlayGameData.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.cauchymop.goblob.proto.PlayGameData.Position prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.cauchymop.goblob.proto.PlayGameData.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.cauchymop.goblob.proto.PlayGameData.internal_static_Position_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.cauchymop.goblob.proto.PlayGameData.internal_static_Position_fieldAccessorTable;
      }
      
      // Construct using com.cauchymop.goblob.proto.PlayGameData.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        x_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        y_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.cauchymop.goblob.proto.PlayGameData.Position.getDescriptor();
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.Position getDefaultInstanceForType() {
        return com.cauchymop.goblob.proto.PlayGameData.Position.getDefaultInstance();
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.Position build() {
        com.cauchymop.goblob.proto.PlayGameData.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.cauchymop.goblob.proto.PlayGameData.Position buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.cauchymop.goblob.proto.PlayGameData.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.cauchymop.goblob.proto.PlayGameData.Position buildPartial() {
        com.cauchymop.goblob.proto.PlayGameData.Position result = new com.cauchymop.goblob.proto.PlayGameData.Position(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.x_ = x_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.y_ = y_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.cauchymop.goblob.proto.PlayGameData.Position) {
          return mergeFrom((com.cauchymop.goblob.proto.PlayGameData.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.cauchymop.goblob.proto.PlayGameData.Position other) {
        if (other == com.cauchymop.goblob.proto.PlayGameData.Position.getDefaultInstance()) return this;
        if (other.hasX()) {
          setX(other.getX());
        }
        if (other.hasY()) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasX()) {
          
          return false;
        }
        if (!hasY()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              x_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              y_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 x = 1;
      private int x_ ;
      public boolean hasX() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getX() {
        return x_;
      }
      public Builder setX(int value) {
        bitField0_ |= 0x00000001;
        x_ = value;
        onChanged();
        return this;
      }
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000001);
        x_ = 0;
        onChanged();
        return this;
      }
      
      // required int32 y = 2;
      private int y_ ;
      public boolean hasY() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getY() {
        return y_;
      }
      public Builder setY(int value) {
        bitField0_ |= 0x00000002;
        y_ = value;
        onChanged();
        return this;
      }
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000002);
        y_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Position)
    }
    
    static {
      defaultInstance = new Position(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Position)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_GameData_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GameData_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Move_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Move_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Position_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Position_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024play-game-data.proto\"\030\n\010GameData\022\014\n\004mo" +
      "ve\030\001 \003(\005\"a\n\004Move\022\034\n\004type\030\001 \002(\0162\016.Move.Mo" +
      "veType\022\033\n\010position\030\002 \001(\0132\t.Position\"\036\n\010M" +
      "oveType\022\010\n\004MOVE\020\000\022\010\n\004PASS\020\001\" \n\010Position\022" +
      "\t\n\001x\030\001 \002(\005\022\t\n\001y\030\002 \002(\005B\034\n\032com.cauchymop.g" +
      "oblob.proto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_GameData_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_GameData_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_GameData_descriptor,
              new java.lang.String[] { "Move", },
              com.cauchymop.goblob.proto.PlayGameData.GameData.class,
              com.cauchymop.goblob.proto.PlayGameData.GameData.Builder.class);
          internal_static_Move_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Move_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Move_descriptor,
              new java.lang.String[] { "Type", "Position", },
              com.cauchymop.goblob.proto.PlayGameData.Move.class,
              com.cauchymop.goblob.proto.PlayGameData.Move.Builder.class);
          internal_static_Position_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Position_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Position_descriptor,
              new java.lang.String[] { "X", "Y", },
              com.cauchymop.goblob.proto.PlayGameData.Position.class,
              com.cauchymop.goblob.proto.PlayGameData.Position.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
